name: packagist_extensions
description: extension tools
version: 1.1.4
homepage: https://github.com/flutter-packagist/extensions

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^12.2.0
  get: ^4.7.2
  intl: ^0.20.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  synchronized: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: