name: packagist_extensions
description: extension tools
version: 1.1.2
homepage: https://github.com/flutter-packagist/extensions

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.0
  get: ^4.6.6
  intl: ^0.19.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: